language: cpp

compiler: gcc

script: make

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libudev-dev

env:
  global:
    - CC=/usr/bin/gcc-4.9
    - CXX=/usr/bin/g++-4.9

branches:
  only:
    - barrier
